---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywelcomepage
  labels: 
    app: mywelcomepage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywelcomepage
  template:
    metadata:
      labels:
        app: mywelcomepage
    spec:
      containers:
      - name: mywelcomepage
        image: bndah/mywelcomepage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: mywelcomepage
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 5000
      nodePort: 31000
  selector:
    app: mywelcomepage
